# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

#browsing
"twitch" = ""
"youtube" = ""
"invidious" = ""
"reddit" = ""
"brave" = ""
"chrome" = ""

#terminal applications
"vim" = "_"
"alacritty" = ""

#communication
"signal" = ""
"franz" = ""
"whatsapp" = ""
"telegram" = ""
"telegram-desktop" = ""
"discord" = ""
"teamspeak" = ""
"thunderbird" = ""
"proton" = ""
"teams-for-linux" = ""

#images and pdfs
"gimp" ="󱇣" 
"gthumb" = ""
"feh" = ""
"image" = ""
".pdf" = ""

#files
"nautilus" = ""
"Vifm" = ""

#gaming
"steam" = ""
"heroic" = ""

#rest
"calendar" = ""
"spotify" = ""
"github" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"transmission" = ""
"music" = ""
"mpv" = ""
"teamviewer" = "󰔀"
[other]
fallback_icon = "󰍹"
deduplicate_icons = true
