# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.
"reddit" = ""
"gimp" ="󱇣" 
"twitch" = ""
"youtube" = ""
"whatsapp" = ""
"brave" = ""
"chrome" = ""
"vim" = ""
"nautilus" = ""
"Vifm" = ""
"alacritty" = ""
"calculator" = ""
"calendar" = ""
"discord" = ""
"disk usage" = ""
"spotify" = ""
"github" = ""
"rust" = ""
"thunderbird" = ""
"tutanota" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"libreoffice calc" = ""
"libreoffice writer" = ""
"libreoffice" = ""
"gthumb" = ""
"feh" = ""
"menu" = ""
"transmission" = ""
"videostream" = ""
"mpv" = ""
"music" = ""
".pdf" = ""
"signal" = ""
"franz" = ""
"steam" = ""
"heroic" = ""
[other]
fallback_icon = " "
deduplicate_icons = true
