# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

#browsing
"twitch" = ""
"youtube" = ""
#"youtube" = ""
"invidious" = ""
"prime" = ""
"amazon" = ""
"reddit" = ""
"todoist" = ""
"audible" = ""
"soundcloud" = ""
"duckduckgo" = "󰇥"
"teams" = ""
"brave" = ""
"Brave-browser" = ""
"chrome" = ""
"overleaf" = " "

#terminal applications
#"vim" = "_"
"vim" = " "
"nvim" = " "
"alacritty" = "󱧶 "
"kitty" = ""
"xterm" = ""
"volume control" = ""

#communication
"signal" = ""
"franz" = ""
"whatsapp" = ""
"telegram" = ""
"telegram-desktop" = ""
"discord" = ""
"teamspeak" = ""
"thunderbird" = ""
"proton" = ""
"webmail" = ""
"teams-for-linux" = ""

#images and pdfs
"gimp" ="󱇣" 
"gthumb" = ""
"feh" = ""
".pdf" = "`"
"okular" = "`"
"image" = ""

#files
"nautilus" = ""
"vifm" = ""

#gaming
"steam" = ""
"heroic" = ""
"unity" = ""

#rest
"windsurf" = "󱝆 "
"cursor" = "󰆽 "
"code" = "󰨞 "
"calendar" = ""
"reminders" = ""
"spotify" = ""
"github" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"transmission" = ""
"music" = ""
"mpv" = ""
"teamviewer" = "󰔀"
"bitwarden" = ""
[other]
fallback_icon = "󰍹 "
deduplicate_icons = true
