# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

#terminal applications
"ranger" = ""
"vifm" = ""
"vim" = " "
"nvim" = " "
"alacritty" = ""
"kitty" = ""

"calendar" = ""
"NextcloudCalendar" = ""
"whatsapp" = ""
"thunderbird" = ""
"proton" = ""
"webmail" = ""
#browsing
"consorsbank" = ""
"twitch" = ""
"youtube" = ""
"invidious" = ""
"prime" = ""
"amazon" = ""
"reddit" = ""
"todoist" = ""
"audible" = ""
"soundcloud" = ""
"duckduckgo" = "󰇥"
"teams" = ""
"overleaf" = " "
"photos" = ""
"brave" = ""
"chrome" = ""

"xterm" = ""
"volume control" = ""

#communication
"signal" = ""
"franz" = ""
"telegram" = ""
"telegram-desktop" = ""
"discord" = ""
"teamspeak" = ""
"teams-for-linux" = ""

#images and pdfs
"gimp" ="󱇣" 
"gthumb" = ""
"feh" = ""
".pdf" = "`"
"okular" = "`"
"image" = ""
"blender" = "󰂫"

#files
"nautilus" = ""

#gaming
"steam" = ""
"heroic" = ""
"unity" = ""

#rest
"windsurf" = "󱝆 "
"cursor" = "󰆽 "
"code" = "󰨞 "
"reminders" = ""
"spotify" = ""
"github" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"transmission" = ""
"music" = ""
"mpv" = ""
"teamviewer" = "󰔀"
"bitwarden" = ""
[other]
fallback_icon = "󰍹 "
deduplicate_icons = true
