# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

#browsing
"twitch" = ""
"youtube" = " "
"invidious" = " "
"reddit" = ""
"todoist" = ""
"audible" = ""
"soundcloud" = ""
"teams" = ""
"brave" = ""
"chrome" = ""

#terminal applications
#"vim" = "_"
"vim" = "."
"alacritty" = ""
"xterm" = ""
"volume control" = ""

#communication
"signal" = ""
"franz" = ""
"whatsapp" = ""
"telegram" = ""
"telegram-desktop" = ""
"discord" = ""
"teamspeak" = ""
"thunderbird" = ""
"proton" = ""
"webmail" = ""
"teams-for-linux" = ""

#images and pdfs
"gimp" ="󱇣" 
"gthumb" = ""
"feh" = ""
"image" = ""
".pdf" = "`"
"okular" = "`"

#files
"nautilus" = ""
"Vifm" = ""

#gaming
"steam" = ""
"heroic" = ""
"unity" = ""

#rest
"cursor" = "󰂮 "
"code" = "󰨞"
"calendar" = ""
"reminders" = ""
"spotify" = ""
"github" = ""
"google" = ""
"private browsing" = ""
"firefox" = ""
"transmission" = ""
"music" = ""
"mpv" = ""
"teamviewer" = "󰔀"
"bitwarden" = ""
[other]
fallback_icon = "󰍹."
deduplicate_icons = true
